// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgPwt5E5Mh45qVL8Q8th3j9svZYmYhejY',
    appId: '1:603019458986:web:0d523e429bec0a8ae2d3d3',
    messagingSenderId: '603019458986',
    projectId: 'adventurerides-ac4b7',
    authDomain: 'adventurerides-ac4b7.firebaseapp.com',
    storageBucket: 'adventurerides-ac4b7.appspot.com',
    measurementId: 'G-801BX2SD8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAowfWwu7aexlHkIo-XHZPVSYFtSaN0pZ8',
    appId: '1:603019458986:android:d4ddfb1200f7df59e2d3d3',
    messagingSenderId: '603019458986',
    projectId: 'adventurerides-ac4b7',
    storageBucket: 'adventurerides-ac4b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2m-fbjDUmy4Pk9PaXGxh2Ntgt7-wsRR4',
    appId: '1:603019458986:ios:6ebe6ff1b8f4b00fe2d3d3',
    messagingSenderId: '603019458986',
    projectId: 'adventurerides-ac4b7',
    storageBucket: 'adventurerides-ac4b7.appspot.com',
    androidClientId: '603019458986-2bma9s1je5a2c53vbqn498ck8o6jt57j.apps.googleusercontent.com',
    iosClientId: '603019458986-d1b6ab4gg0vl5jucbv51ft3id8v75l5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.adventureRides',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2m-fbjDUmy4Pk9PaXGxh2Ntgt7-wsRR4',
    appId: '1:603019458986:ios:6ebe6ff1b8f4b00fe2d3d3',
    messagingSenderId: '603019458986',
    projectId: 'adventurerides-ac4b7',
    storageBucket: 'adventurerides-ac4b7.appspot.com',
    androidClientId: '603019458986-2bma9s1je5a2c53vbqn498ck8o6jt57j.apps.googleusercontent.com',
    iosClientId: '603019458986-d1b6ab4gg0vl5jucbv51ft3id8v75l5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.adventureRides',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgPwt5E5Mh45qVL8Q8th3j9svZYmYhejY',
    appId: '1:603019458986:web:3570bdb0d36e9cede2d3d3',
    messagingSenderId: '603019458986',
    projectId: 'adventurerides-ac4b7',
    authDomain: 'adventurerides-ac4b7.firebaseapp.com',
    storageBucket: 'adventurerides-ac4b7.appspot.com',
    measurementId: 'G-6G96FFMCPC',
  );
}
